### PR TITLE
Pull_Request # Wed_Hawks

### PR DESCRIPTION
**Pull request by Gatera-Me**
You have never come in contact with the very alarm for any natural surprise! Have you? PREDICTIVE ANALYTIC ON COMPLEX SYSTEM, At Your Service!

Enables rapid response, preparedness, and mitigation for natural disasters.

### CODE REVIEW

**Comment by ishimwe-joyeuse** [comment]
Good

**Comment by BorisIra19** [comment]
Agree

**Comment by Mireille05** [comment]
well done

**Comment by SandrineMerci** [comment]
This is the best

**Comment by SanoArmel** [comment]
Well done

**Comment by leonmayanja** [comment]
Good

**Comment by Sabour-yacoub** [comment]
great

**Comment by ishimwe-joyeuse** [comment]
well done

**Comment by Mireille05** [comment]
Good

**Comment by BorisIra19** [comment]
good

**Pull request merged**
